In [ ]:
## If you want to set the seed that calls to np.random... will use, use np.random.seed:

np.random.seed(1234)
np.random.uniform(0, 10, 5)
# array([ 1.9151945 ,  6.22108771,  4.37727739,  7.85358584,  7.79975808])
np.random.rand(2,3)
# array([[ 0.27259261,  0.27646426,  0.80187218],
#       [ 0.95813935,  0.87593263,  0.35781727]])

## If you want to use the random state class, you must save an instance of the class, initiated with a seed:

r = np.random.RandomState(1234)
r.uniform(0, 10, 5)
#array([ 1.9151945 ,  6.22108771,  4.37727739,  7.85358584,  7.79975808])
And it maintains the state just as before:

r.rand(2,3)
#array([[ 0.27259261,  0.27646426,  0.80187218],
#       [ 0.95813935,  0.87593263,  0.35781727]])

## You can see the state of the sort of 'global' class with
np.random.get_state()
## and of your own class instance with
r.get_state()

In [4]:
import numpy as np

# data generation
x = np.linspace(0, 10, 100)
rng = np.random.RandomState(0)
print rng.get_state()
print x, rng
rng.shuffle(x)
print x

('MT19937', array([         0,          1, 1812433255, 1900727105, 1208447044,
       2481403966, 4042607538,  337614300, 3232553940, 1018809052,
       3202401494, 1775180719, 3192392114,  594215549,  184016991,
        829906058,  610491522, 3879932251, 3139825610,  297902587,
       4075895579, 2943625357, 3530655617, 1423771745, 2135928312,
       2891506774, 1066338622,  135451537,  933040465, 2759011858,
       2273819758, 3545703099, 2516396728, 1272276355, 3172048492,
       3267256201, 2332199830, 1975469449,  392443598, 1132453229,
       2900699076, 1998300999, 3847713992,  512669506, 1227792182,
       1629110240,  112303347, 2142631694, 3647635483, 1715036585,
       2508091258, 1355887243, 1884998310, 3906360088,  952450269,
       3647883368, 3962623343, 3077504981, 2023096077, 3791588343,
       3937487744, 3455116780, 1218485897, 1374508007, 2815569918,
       1367263917,  472908318, 2263147545, 1461547499, 4126813079,
       2383504810,   64750479, 2963140275, 1709368