**This notebook show how the check the __doc__, np.source(), and github checklist of a function/method**

1. `gradient`: The gradient is computed using second order accurate central differences in the interior and either first differences or second order accurate one-sides (forward or backwards) differences at the boundaries. The returned gradient hence has the same shape as the input array.
    For two dimensional arrays, the return will be two arrays ordered by axis. In this example the first array stands for the gradient in rows and the second one in columns direction:
    
Find the formula from the github changelist.
   
* edge_order = 2:

    ```
      The one-sided boundary gradient uses 3 elements each with a different weight. A
      forward difference is used for the first element,
         dy/dx = f'(0) ~ (3.0*y[0] - 4.0*y[1] + y[2]) / (2.0*dx)
      and backwards difference is used for the last element,
         dy/dx = f'(-1) ~ (3.0*y[-1] - 4.0*y[-2] + y[-3]) / (2.0*dx)
    ```
    
* edge_order = 1:

    ```
      The one-sided boundary gradient uses 2 elements each with a different weight. A
      forward difference is used for the first element,
         dy/dx = f'(0) ~ (y[1] - y[0]) / dx
      and backwards difference is used for the last element,
         dy/dx = f'(-1) ~ (y[-1] - y[-2]) / dx
    ```

In [12]:
from numpy import *
x = np.array([-4, -3, -2, -1, 0, 1, 2, 3, 4])
dx = np.gradient(x)
print dx

y = x**2
dy0 = gradient(y, edge_order=1)
dy = gradient(y, dx, edge_order=2)
print dy0, dy
dSgn = sign(dy)
print dSgn
d_dSgn = gradient(dSgn)
print d_dSgn

# that's the line, you need:
a = diff(sign(diff(y))).nonzero()[0] + 1 # local min+max
b = (diff(sign(diff(y))) > 0).nonzero()[0] + 1 # local min
c = (diff(sign(diff(y))) < 0).nonzero()[0] + 1 # local max
print b

[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
[-7. -6. -4. -2.  0.  2.  4.  6.  7.] [-8. -6. -4. -2.  0.  2.  4.  6.  8.]
[-1. -1. -1. -1.  0.  1.  1.  1.  1.]
[ 0.   0.   0.   0.5  1.   0.5  0.   0.   0. ]
(array([3, 4, 5]),)


In [14]:
#print(np.gradient.__doc__)
print(np.nonzero.__doc__)


    Return the indices of the elements that are non-zero.

    Returns a tuple of arrays, one for each dimension of `a`,
    containing the indices of the non-zero elements in that
    dimension. The values in `a` are always tested and returned in
    row-major, C-style order. The corresponding non-zero
    values can be obtained with::

        a[nonzero(a)]

    To group the indices by element, rather than dimension, use::

        transpose(nonzero(a))

    The result of this is always a 2-D array, with a row for
    each non-zero element.

    Parameters
    ----------
    a : array_like
        Input array.

    Returns
    -------
    tuple_of_arrays : tuple
        Indices of elements that are non-zero.

    See Also
    --------
    flatnonzero :
        Return indices that are non-zero in the flattened version of the input
        array.
    ndarray.nonzero :
        Equivalent ndarray method.
    count_nonzero :
        Counts the number of non-zero elements in the input arr

In [7]:
np.source(np.gradient)

In file: C:\Users\peyang\AppData\Local\Continuum\Anaconda2\lib\site-packages\numpy\lib\function_base.py

def gradient(f, *varargs, **kwargs):
    """
    Return the gradient of an N-dimensional array.

    The gradient is computed using second order accurate central differences
    in the interior and either first differences or second order accurate
    one-sides (forward or backwards) differences at the boundaries. The
    returned gradient hence has the same shape as the input array.

    Parameters
    ----------
    f : array_like
        An N-dimensional array containing samples of a scalar function.
    varargs : list of scalar, optional
        N scalars specifying the sample distances for each dimension,
        i.e. `dx`, `dy`, `dz`, ... Default distance: 1.
    edge_order : {1, 2}, optional
        Gradient is calculated using N\ :sup:`th` order accurate differences
        at the boundaries. Default: 1.

        .. versionadded:: 1.9.1

    Returns
    -------
    gradient 

Apparently the way gradients are calculated was changed between 1.8.1 and 1.9.0 by [332d628](https://github.com/numpy/numpy/commit/332d628744a0670234585053dbe32a3e82e0c4db)

In [15]:
from numpy import *

# example data with some peaks:
x = linspace(0,4,1e3)
data = .2*sin(10*x)+ exp(-abs(2-x)**2)

# that's the line, you need:
a = diff(sign(diff(data))).nonzero()[0] + 1 # local min+max
b = (diff(sign(diff(data))) > 0).nonzero()[0] + 1 # local min
c = (diff(sign(diff(data))) < 0).nonzero()[0] + 1 # local max


# graphical output...
from pylab import *
plot(x,data)
plot(x[b], data[b], "o", label="min")
plot(x[c], data[c], "o", label="max")
legend()
show()

In [16]:
b

array([114, 265, 425, 597, 755, 905])

In [18]:
print(plt.legend.__doc__)

Places a legend on the axes.

To make a legend for lines which already exist on the axes
(via plot for instance), simply call this function with an iterable
of strings, one for each legend item. For example::

    ax.plot([1, 2, 3])
    ax.legend(['A simple line'])

However, in order to keep the "label" and the legend element
instance together, it is preferable to specify the label either at
artist creation, or by calling the
:meth:`~matplotlib.artist.Artist.set_label` method on the artist::

    line, = ax.plot([1, 2, 3], label='Inline label')
    # Overwrite the label by calling the method.
    line.set_label('Label via method')
    ax.legend()

Specific lines can be excluded from the automatic legend element
selection by defining a label starting with an underscore.
This is default for all artists, so calling :meth:`legend` without
any arguments and without setting the labels manually will result in
no legend being drawn.

For full control of which artists have a legend entry, it is

In [19]:
print(plt.plot.__doc__)

Plot lines and/or markers to the
:class:`~matplotlib.axes.Axes`.  *args* is a variable length
argument, allowing for multiple *x*, *y* pairs with an
optional format string.  For example, each of the following is
legal::

    plot(x, y)        # plot x and y using default line style and color
    plot(x, y, 'bo')  # plot x and y using blue circle markers
    plot(y)           # plot y using x as index array 0..N-1
    plot(y, 'r+')     # ditto, but with red plusses

If *x* and/or *y* is 2-dimensional, then the corresponding columns
will be plotted.

An arbitrary number of *x*, *y*, *fmt* groups can be
specified, as in::

    a.plot(x1, y1, 'g^', x2, y2, 'g-')

Return value is a list of lines that were added.

By default, each line is assigned a different color specified by a
'color cycle'.  To change this behavior, you can edit the
axes.color_cycle rcParam.

The following format string characters are accepted to control
the line style or marker:

================    ====================

In [21]:
Amax = [  39,  117,  197,  280,  367,  456,  561,  655,  761,  849,  943,
        1057, 1151, 1239, 1345, 1439, 1544, 1634, 1720, 1804, 1885, 1961]
Rmax = [ 39,   75,  117,  155,  197,  238,  280,  323,  367,  413,  456,
         529,  561,  620,  655,  722,  761,  809,  849,  896,  943, 1000,
        1057, 1104, 1151, 1191, 1239, 1278, 1345, 1380, 1439, 1471, 1544,
        1587, 1634, 1678, 1720, 1763, 1804, 1847, 1885, 1928, 1961, 1997]

Amin = [  75,  155,  238,  323,  413,  529,  619,  722,  809,  895, 1000,
        1105, 1191, 1279, 1381, 1471, 1587, 1678, 1763, 1847, 1928, 1997]
Rmin = [  13,   64,   89,  144,  169,  226,  251,  310,  336,  398,  425,
         516,  537,  602,  627,  698,  730,  795,  814,  887,  899,  996,
        1004, 1101, 1113, 1185, 1205, 1270, 1302, 1373, 1398, 1463, 1484,
        1574, 1602, 1664, 1690, 1749, 1775, 1833, 1858, 1914, 1938, 1985]
lnAmax = len(Amax)
count = 0
for n in Amax:
    if n in Rmax:
        count += 1
print count, lnAmax

lnAmin = len(Amin)
count = 0
for n in Amin:
    if n in Rmin:
        count += 1
print count, lnAmin

22 22
0 22


In [25]:
a = np.array([ 102,  225,  379,  504,  652,  799,  923, 1076, 1201, 1347, 1495,
       1618, 1772, 1896])
print len(a), a[1]

14 225
